pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    triggers {
        // Equivalent of ticking "GitHub hook trigger for GITScm polling" on the job.
        // GitHub's webhook (relayed through smee.io to /github-webhook/) starts the build.
        githubPush()
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t team-skeleton:${BUILD_NUMBER} .'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -B test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
